name: Build express

on:
  workflow_dispatch:
    inputs:
      folders:
        description: 'Start Workflow and Build'
        required: true
        default: '1.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ghcr

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/expressfs:1.0